# Generated by Django 5.0.3 on 2024-03-17 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 20, 35, 42, 61805, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 20, 35, 42, 61805, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
