# Generated by Django 5.0.3 on 2024-03-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('text', models.TextField(verbose_name='text')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='preview')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
    ]
