# Generated by Django 5.0.3 on 2024-04-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_publication_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Can publish products'), ('change_description', 'Can change description'), ('change_category', 'Can change product category')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
