# Generated by Django 5.0.3 on 2024-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
